### PR TITLE
Add --ext option

### PR DESCRIPTION
**Pull request by vecchp**
This PR adds the ability to pass which file extensions lint-diff looks for (since right now we only do .js).

- Also update peerDependency for eslint to be >=4.x
- Upgrade ramda to 0.26.1
- Replace pipeP with pipeWith as pipeP is deprecated.

### CODE REVIEW

**Comment by vecchp** [comment]
@grvcoelho ,This should be ready for review.

**Comment by shoesel** [comment]
yes, pls

**Comment by vecchp** [comment]
@shoesel , I made a release based off this PR in the interim if you want to use it. https://github.com/vecchp/lint-diff/releases/download/v1.3.0/lint-diff-1.3.0.tgz

**Comment by vecchp** [comment]
@grvcoelho is this project still maintained?

**Comment by vecchp** [comment]
@grvcoelho , any chance you'd be able to review this PR?

**Comment by joker-777** [comment]
This feature would be awesome!

**Comment by joker-777** [comment]
@vecchp It looks like this project isn't maintained anymore. Could you publish your version to npm?

**Comment by vecchp** [comment]
Sure, I'll try and get around to that this evening

**Comment by vecchp** [comment]
I didn't have a chance last night but I'll make my best effort to publish it soon.

**Comment by vecchp** [comment]
Should be published as `@vecchp/lint-diff@1.3.0` now

**Comment by vecchp** [comment]
We are considering moving to this plugin in favor of lint-diff: https://github.com/paleite/eslint-plugin-diff

**Pull request closed without merging**
